# Generated by Django 4.2.17 on 2024-12-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={},
        ),
        migrations.AlterField(
            model_name="story",
            name="author",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="story",
            name="expanded_plot",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
