# Generated by Django 4.2.17 on 2025-01-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_story_options_alter_story_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="expanded_plot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
