# Generated by Django 4.2.17 on 2025-01-09 06:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=50)),
                ("archetype", models.CharField(max_length=50)),
                (
                    "personality_traits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "motivations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        size=None,
                    ),
                ),
                ("backstory", models.TextField()),
                ("emotional_state", models.CharField(default="neutral", max_length=50)),
                ("character_arc", models.TextField(blank=True, null=True)),
                ("relationships", models.JSONField(default=dict)),
                ("plot_importance", models.IntegerField(default=1)),
                ("custom_attributes", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-plot_importance"],
            },
        ),
        migrations.CreateModel(
            name="CharacterRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relationship_type", models.CharField(max_length=50)),
                ("intensity", models.IntegerField(default=5)),
                ("dynamic", models.BooleanField(default=True)),
                (
                    "character1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_char1",
                        to="characters.character",
                    ),
                ),
                (
                    "character2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_char2",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "unique_together": {("character1", "character2")},
            },
        ),
    ]
