# Generated by Django 4.2.17 on 2025-01-10 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0002_character_story"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterArc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plot_point", models.TextField()),
                ("emotional_change", models.TextField()),
                ("motivation", models.TextField()),
                ("sequence_number", models.IntegerField()),
            ],
            options={
                "ordering": ["sequence_number"],
            },
        ),
        migrations.AlterModelOptions(
            name="character",
            options={},
        ),
        migrations.RenameField(
            model_name="character",
            old_name="backstory",
            new_name="background",
        ),
        migrations.RemoveField(
            model_name="character",
            name="archetype",
        ),
        migrations.RemoveField(
            model_name="character",
            name="character_arc",
        ),
        migrations.RemoveField(
            model_name="character",
            name="custom_attributes",
        ),
        migrations.RemoveField(
            model_name="character",
            name="motivations",
        ),
        migrations.RemoveField(
            model_name="character",
            name="personality_traits",
        ),
        migrations.RemoveField(
            model_name="character",
            name="plot_importance",
        ),
        migrations.AddField(
            model_name="character",
            name="appearance",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="character",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="character",
            name="goals",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="character",
            name="personality",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="character",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="emotional_state",
            field=models.TextField(default="{}"),
        ),
        migrations.AlterField(
            model_name="character",
            name="relationships",
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name="CharacterRelationship",
        ),
        migrations.AddField(
            model_name="characterarc",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_arcs",
                to="characters.character",
            ),
        ),
    ]
