# Generated by Django 4.2.17 on 2025-01-11 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_characterarc_alter_character_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_number', models.IntegerField()),
                ('dialogue_text', models.TextField()),
                ('emotion', models.CharField(max_length=50)),
                ('sequence_number', models.IntegerField()),
            ],
            options={
                'ordering': ['scene_number', 'sequence_number'],
            },
        ),
        migrations.RemoveField(
            model_name='character',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='character',
            name='emotional_state',
        ),
        migrations.RemoveField(
            model_name='character',
            name='personality',
        ),
        migrations.AddField(
            model_name='character',
            name='personality_traits',
            field=models.JSONField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='relationships',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='CharacterArc',
        ),
        migrations.AddField(
            model_name='characterdialogue',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='characters.character'),
        ),
    ]
